version: "3"

services:

  rentalapp:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - rentalapp-postgres
      - rentalapp-redis
    ports:
      - "8010:8010"
    env_file:
      - .env

  rentalapp-postgres:
    image: postgres
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432"
    restart: always

  rentalapp-redis:
    image: redis:alpine
    expose:
      - 6379

  rentalapp-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:8020"
    volumes:
      - ./:/var/www
    depends_on:
      - rentalapp

networks:
  default:
    external:
      name: rails-api-network